version: '3.8'

services:
  eureka-server:
    container_name: eureka
    build:
      context: C:\Users\Khalifa\Desktop\micro_services\MyEureka\post\post
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  post-app:
    container_name: post-app
    build:
      context: C:\Users\Khalifa\Desktop\micro_services\MyEureka\post\post
      dockerfile: Dockerfile
    env_file: ./.env
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
            "spring.datasource.username" : "$MYSQLDB_USER",
            "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update",
            "eureka.client.service-url.defaultZone":"http://eureka-server:8761/eureka/"
          }'
        #- MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
        #- MYSQL_DATABASE=$MYSQLDB_DATABASE
        #- MYSQL_ALLOW_EMPTY_PASSWORD=true
    depends_on:
      - mysqldb
      - eureka-server
    ports:
      - "8083:8083"
    logging:
      driver: "json-file"
      options:
        max-file: "5"   # number of files or file count
        max-size: "10m" # file size
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
volumes:
  db: